name: pikpak_auto_invite
on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '!.gitignore'
      - '!README.md'
  schedule:
    # 每天晚六点十分执行一次
    - cron:  '10 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Time
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run
        env:
          INVITE_CODE: ${{secrets.INVITE_CODE}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
        run: python run.py
